# ==============================
# Project Identification
# ==============================
sonar.projectKey=pde_ui
sonar.projectName=PDE_UI
sonar.projectVersion=1.0

# ==============================
# Source Configuration
# ==============================
sonar.sources=.
sonar.sourceEncoding=UTF-8

# ==============================
# SonarQube Server
# ==============================
sonar.host.url=http://10.10.120.20:9000
sonar.token=sqp_abc57ecbb8de50c0399ed8f26091028e306baa8d

# ==============================
# Exclusions
# ==============================
sonar.exclusions=node_modules/**,dist/**,build/**,.next/**,coverage/**

# ==============================
# JavaScript/TypeScript Settings
# ==============================
sonar.javascript.lcov.reportPaths=coverage/lcov.info
