let covenantType = {
       saleMessage: [
              { value: "The VENDOR hereby declares that the vendor is the rightful owner, and is having full right and absolute authority to convey the schedule property to the VENDEE and that the schedule property is free from all kinds of encumbrances, charges, lien, claims and demands of whatsoever nature and that the vendor has paid all taxes etc., payable on the schedule property up to date and there are no dues of any kind against the said property.The VENDOR hereby sell, convey and transfer the schedule property with all rights, title, interest whatsoever of the VENDOR to have and to hold the same as absolute owner to the use of the VENDEE forever. " },
              { value: "The VENDOR herein delivered the vacant and peaceful physical possession of the schedule property to the VENDEE on this day and the VENDEE who shall hereafter is entitled to peacefully hold, use and enjoy the schedule property as his own property without any hindrance, interruption, claim or demand by or from the VENDOR or any other person claiming through vendor, whomsoever. " },
              { value: "Whereas the VENDOR declare that the property has not been conveyed or alienated to any other person in any way by the vendor, his heirs, executors, administrators, representatives and assigns through any other document earlier and agrees to keep indemnified the VENDEE from and against all losses, costs, damages, charges and expenses, if any suffered by reason of any defect in the title of the vendor or any breach of the covenants and the vendor shall be held responsible, if any discrepancy is found in future. " },
              { value: "The Vendor shall do and execute or cause to be done and executed all such lawful acts, deeds and things whatsoever for further and more perfectly conveying the schedule property and for mutation of name in all the concerned offices. " }
       ],
       mortgageMessage: [
              { value: "As security for the repayment of  the above loan the MORTGAGOR hereby create charge by way of simple mortgage the property morefully described in the schedule hereunder in favour of the MORTGAGEE. " },
              { value: "That if the said principal sum or sums of money herein before  covenanted to be paid with interest at the rate and within the period stipulated is not be duly paid or if MORTGAGOR(S) fails and/or neglects to complete this obligation, in so doing the MORTGAGEE(S)s shall have the right to enforce the security hereunder created and to sell the property and realise out of the proceeds of such sale all sums due to them together with principal and interest after paying the costs and expenses  of such sale and if the MORTGAGEE(S)s debt is still unsatisfied,  the MORTGAGEE(S)s may enforce the loan against the person or other property of the MORTGAGOR(S) and in case  of there being surplus, the same shall be refunded to the MORTGAGOR(S). And the MORTGAGOR(S) shall reimburse all the sums paid by the MORTGAGEE(S)s on behalf of the MORTGAGOR(S). And also that if any expenditure incurred by the MORTGAGEE(S)s towards postal, registration charges, court expenses etc. shall be debited to the Principle amount and shall carry interest as mentioned above. As a security for the due repayment of all monies due under this deed, the MORTGAGOR(S) hereby mortgage without possession with MORTGAGEE(S)s all the scheduled property as said above." }
       ],
       giftMessage: [
              { value: "The SETTLOR herein delivered the vacant and peaceful physical possession of the schedule property to the SETTLEE on this day and the SETTLEE who shall hereafter is entitled to peacefully hold, use and enjoy the schedule property as his own property without any hindrance, interruption, claim or demand by or from the SETTLOR or any other person claiming through SETTLOR, whomsoever." },
              { value: "Whereas the SETTLOR declare that the property has not been conveyed or alienated to any other person in any way by the SETTLOR, his heirs, executors, administrators, representatives and assigns through any other document earlier and agrees to keep indemnified the SETTLEE from and against all losses, costs, damages, charges and expenses, if any suffered by reason of any defect in the title of the SETTLOR or any breach of the covenants and the SETTLOR shall be held responsible, if any discrepancy is found in future. " },
              { value: "The SETTLOR shall do and execute or cause to be done and execute all such lawful acts, deeds and things whatsoever for the mutation of name in all the concerned offices. " },
              { value: "Whereas the SETTLOR declares that all the facts and statutory provisions required by the Acts such as Registration Act, Indian Stamp Act, Transfer of Property Act, Evidence Act and Other allied statutory Acts have been complied with.  If any suppression of facts or violations of the provisions of the above stated statutes or any of the stipulations preferred through Government Orders are noticed at a future date, the parties concerned will be held liable for prosecution as per law besides payment of deficit duty i.e., total loss sustained by the Government along with the stipulated penalties and this transaction is liable to be declared as null and void besides prosecution.The SETTLOR hereby declares that the schedule property is not a prohibited property and the schedule property is not under any injunction by any Court of Law." },
              { value: "The SETTLOR herein delivered the vacant and peaceful physical possession of the schedule property to the SETTLEE on this day and the SETTLEE who shall hereafter is entitled to peacefully hold, use and enjoy the schedule property as his own property without any hindrance, interruption, claim or demand by or from the SETTLOR or any other person claiming through SETTLOR, whomsoever." },
              { value: "Whereas the SETTLOR declare that the property has not been conveyed or alienated to any other person in any way by the SETTLOR, his heirs, executors, administrators, representatives and assigns through any other document earlier and agrees to keep indemnified the SETTLEE from and against all losses, costs, damages, charges and expenses, if any suffered by reason of any defect in the title of the SETTLOR or any breach of the covenants and the SETTLOR shall be held responsible, if any discrepancy is found in future. " },
              { value: "The SETTLOR shall do and execute or cause to be done and execute all such lawful acts, deeds and things whatsoever for the mutation of name in all the concerned offices. " },
              { value: "Whereas the SETTLOR declares that all the facts and statutory provisions required by the Acts such as Registration Act, Indian Stamp Act, Transfer of Property Act, Evidence Act and Other allied statutory Acts have been complied with.  If any suppression of facts or violations of the provisions of the above stated statutes or any of the stipulations preferred through Government Orders are noticed at a future date, the parties concerned will be held liable for prosecution as per law besides payment of deficit duty i.e., total loss sustained by the Government along with the stipulated penalties and this transaction is liable to be declared as null and void besides prosecution.The SETTLOR hereby declares that the schedule property is not a prohibited property and the schedule property is not under any injunction by any Court of Law." },
       ]
}

export default covenantType;