let MasterData = {
    StageOfCons: [
        { code: 1, desc: "UP TO FOUNDATION LEVEL [పునాది స్థాయి వరకు]" },
        { code: 2, desc: "UPTO LINTEL LEVEL [లింటెల్ స్థాయి వరకు]" },
        { code: 3, desc: "UP TO SLAB LEVEL/ROOF [స్లాబ్ స్థాయి/పైకప్పు వరకు]" },
        { code: 4, desc: "SEMI-FINISHED [సగం పూర్తయింది]" },
        { code: 5, desc: "FINISHED [పూర్తయింది]" }
    ],
    floorNo: [
        { code: "01", desc: "First Floor" },
        { code: "02", desc: "Second Floor" },
        { code: "03", desc: "Third Floor" },
        { code: "04", desc: "Fourth Floor" },
        { code: "05", desc: "Fifth Floor" },
        { code: "06", desc: "Sixth Floor" },
        { code: "07", desc: "Seventh Floor" },
        { code: "08", desc: "Eight Floor" },
        { code: "09", desc: "Nineth Floor" },
        { code: 10, desc: "Tenth Floor" },
        { code: 11, desc: "Eleventh Floor" },
        { code: 12, desc: "Twelfth Floor" },
        { code: 13, desc: "Thirteenth Floor" },
        { code: 14, desc: "Fourteenth Floor" },
        { code: 15, desc: "Fifteenth Floor" },
        { code: 16, desc: "Sixteenth Floor" },
        { code: 17, desc: "Seventeenth Floor" },
        { code: 18, desc: "Eighteenth Floor" },
        { code: 19, desc: "Nineteenth Floor" },
        { code: 20, desc: "Twentieth Floor" },
        { code: 21, desc: "Twenty First Floor" },
        { code: 22, desc: "Twenty Second Floor" },
        { code: 23, desc: "Twenty Third Floor" },
        { code: 24, desc: "Twenty Fourth Floor" },
        { code: 25, desc: "Twenty Fifth Floor" },
        { code: 26, desc: "Twenty Sixth Floor" },
        { code: 27, desc: "Twenty Seventh Floor" },
        { code: 28, desc: "Twenty Eighth Floor" },
        { code: 29, desc: "Twenty Ninth Floor" },
        { code: 30, desc: "Thirtieth Floor" },
        { code: 31, desc: "Thirty First Floor" },
        { code: 32, desc: "Thirty Second Floor" },
        { code: 33, desc: "Thirty Third Floor" },
        { code: 34, desc: "Thirty Fourth Floor" },
        { code: 35, desc: "Thirty Fifth Floor" },
        { code: 36, desc: "Thirty Sixth Floor" },
        { code: 37, desc: "Thirty Seventh Floor" },
        { code: 38, desc: "Thirty Eighth Floor" },
        { code: 39, desc: "Thirty Ninth Floor" },
        { code: 40, desc: "Fortieth Floor" },
        { code: 41, desc: "Forty First Floor" },
        { code: 42, desc: "Forty Second Floor" },
        { code: 43, desc: "Forty Third Floor" },
        { code: 44, desc: "Forty Fourth Floor" },
        { code: 45, desc: "Forty Fifth Floor" },
        { code: 46, desc: "Forty Sixth Floor" },
        { code: 47, desc: "Forty Seventh Floor" },
        { code: 48, desc: "Forty Eighth Floor" },
        { code: 49, desc: "Forty Ninth Floor" },
        { code: 50, desc: "Fiftieth Floor" },
        { code: 51, desc: "Fifty First Floor" },
        { code: 52, desc: "Fifty Second Floor" },
        { code: 53, desc: "Fifty Third Floor" },
        { code: 54, desc: "Fifty Fourth Floor" },
        { code: 55, desc: "Fifty Fifth Floor" },
        { code: 56, desc: "Fifty Sixth Floor" },
        { code: 57, desc: "Fifty Seventh Floor" },
        { code: 58, desc: "Fifty Eighth Floor" },
        { code: 59, desc: "Fifty Ninth Floor" },
        { code: 60, desc: "Sixtieth Floor" },
        { code: 61, desc: "Sixty First Floor" },
        { code: 62, desc: "Sixty Second Floor" },
        { code: 63, desc: "Sixty Third Floor" },
        { code: 64, desc: "Sixty Fourth Floor" },
        { code: 65, desc: "Sixty Fifth Floor" },
        { code: 66, desc: "Sixty Sixth Floor" },
        { code: 67, desc: "Sixty Seventh Floor" },
        { code: 68, desc: "Sixty Eighth Floor" },
        { code: 69, desc: "Sixty Ninth Floor" },
        { code: 70, desc: "Seventieth Floor" },
        { code: 71, desc: "Seventy First Floor" },
        { code: 72, desc: "Seventy Second Floor" },
        { code: 73, desc: "Seventy Third Floor" },
        { code: 74, desc: "Seventy Fourth Floor" },
        { code: 75, desc: "Seventy Fifth Floor" },
        { code: 76, desc: "Seventy Sixth Floor" },
        { code: 77, desc: "Seventy Seventh Floor" },
        { code: 78, desc: "Seventy Eighth Floor" },
        { code: 79, desc: "Seventy Ninth Floor" },
        { code: 80, desc: "Eightieth Floor" },
        { code: 81, desc: "Eighty First Floor" },
        { code: 82, desc: "Eighty Second Floor" },
        { code: 83, desc: "Eighty Third Floor" },
        { code: 84, desc: "Eighty Fourth Floor" },
        { code: 85, desc: "Eighty Fifth Floor" },
        { code: 86, desc: "Eighty Sixth Floor" },
        { code: 87, desc: "Eighty Seventh Floor" },
        { code: 88, desc: "Eighty Eighth Floor" },
        { code: 89, desc: "Eighty Ninth Floor" },
        { code: 90, desc: "Ninetieth Floor" },
        { code: 91, desc: "Ninty First Floor" },
        { code: 92, desc: "Ninty Second Floor" },
        { code: 93, desc: "Ninty Third Floor" },
        { code: 94, desc: "Ninty Fourth Floor" },
        { code: 95, desc: "Ninty Fifth Floor" },
        { code: 96, desc: "Ninty Sixth Floor" },
        { code: 97, desc: "Ninty Seventh Floor" },
        { code: 98, desc: "Ninty Eighth Floor" },
        { code: 99, desc: "Ninty Ninth Floor" },
        { code: "CE", desc: "Cellar" },
        { code: "FU", desc: "Foundation" },
        { code: "GR", desc: "Ground" },
        { code: "MZ", desc: "Mezzanaine floor" },
        { code: "PA", desc: "Parking" }
    ],
    structureType: [
        { code: "01", desc: "RCC [కాంక్రీటు ఫై కప్పు]" },
        { code: "02", desc: "MUD ROOF [మట్టి పైకప్పు]" },
        { code: "03", desc: "ROOF WITH PALM/GRASS ETC. WITH BRICK WALL [ఇటుక గోడతో/ గడ్డి మొదలైన వాటితో పైకప్పు]" },
        { code: "04", desc: "ROOF WITH PALM/GRASS ETC. WITHOUT BRICK WALL [ఇటుక గోడ లేకుండా/ గడ్డి మొదలైన వాటితో పైకప్పు]" },
        { code: "05", desc: "ACC/M.T/PAN TILE/ SHABAD STONE/ZN SHEET [ACC / M.T / పాన్ టైల్ / షాబాద్ స్టోన్ / జింక్ షీట్]" },
        { code: "06", desc: "ACC/TIN/ZN SHEET ETC WITH WALLS ABOVE 10 FT [ACC / TIN / జింక్ షీట్ మొదలైనవి 10 అడుగుల ఎత్తు కంటే ఎక్కువ గోడలతో]" },
        { code: "07", desc: "POULTRY FARMS [కోళ్ల ఫారం]" },
        { code: "08", desc: "APARTMENT WITHOUT COMMONWALLS ATLEAST 3 SIDES [కనీసం 3 వైపులా కామన్ వాల్స్ లేని అపార్ట్ మెంట్]" },
        { code: "09", desc: "High raise struc with RCC exceeding 10Ft. Height" },
        { code: 10, desc: "Industrial shed with AC/GI sheet roofing 4.27m Hei" },
        { code: 11, desc: "Muiltiplex with Cellar (with vitrified tiles floor" },
        { code: 12, desc: "RCC Building for Pharmaceutical as per GMP standar" },
        { code: 13, desc: "Industrial PEB sheds with Galvalume sheet roofing " },
        { code: 14, desc: "RCC building for Residential complex 3.2m height" }
    ],
    landUse: [
        { code: "01", desc: "RESIDENTIAL (R) [నివాసయోగ్యము(R)]" },
        { code: "02", desc: "COMMERCIAL(R) [వాణిజ్యము(R)]" },
        { code: "03", desc: "Govt. Land (URBAN)" },
        { code: "04", desc: "Assigned Land (URBAN)" },
        { code: "05", desc: "Semi Commercial" },
        { code: "06", desc: "NOTIFIED SLUM(R) [ప్రకటిత మురికివాడ(R)]" },
        { code: "07", desc: "INDUSTRIAL (URBAN)(R) [పారిశ్రామిక సంబంధము(R)]" },
        { code: "08", desc: "Agricultural land fit for H,S." },
        { code: "09", desc: "URBAN VACANT LAND(RESIDENTIAL)(R) [పట్టణ ఖాళీ స్తలము(నివాసం (R )]" },
        { code: 10, desc: "OTHERS" },
        { code: 11, desc: "URBAN VACANT LAND(COMMERCIAL)(R) [పట్టణ ఖాళీ స్తలము(వ్యాపారపరమైన )(R)]" },
        { code: 12, desc: "Demolished House (Residential)" },
        { code: 13, desc: "Demolished House (Commercial)" },
        { code: 21, desc: "DRY LAND(A) [మెట్ట భూమి(A)]" },
        { code: 22, desc: "Dry Land with Bore or openwell" },
        { code: 23, desc: "Dry Land under lift irrigation" },
        { code: 24, desc: "Dry Land with ayacut/check dam" },
        { code: 25, desc: "Dry Land under minor irri." },
        { code: 26, desc: "WET LAND DOUBLE CROP(A)[తడి భూమి రెట్టింపు క్రాప్ (ఎ)]" },
        { code: 27, desc: "Wet Land single crop" },
        { code: 28, desc: "Government Land (RURAL)" },
        { code: 29, desc: "Assigned Land (RURAL)" },
        { code: 30, desc: "GARDEN(A) [తోటలు(A)]" },
        { code: 31, desc: "Sugar cane" },
        { code: 32, desc: "Turmeric" },
        { code: 33, desc: "Betel leaves" },
        { code: 34, desc: "Arecaout Garden" },
        { code: 35, desc: "Mango garden" },
        { code: 36, desc: "Fruit Garden ie. Guava etc" },
        { code: 37, desc: "Other Horticulture crops" },
        { code: 38, desc: "Floriculture" },
        { code: 39, desc: "Pisci culture" },
        { code: 40, desc: "Prawn culture" },
        { code: 41, desc: "Poultry Farming" },
        { code: 42, desc: "Goat/Sheep farm" },
        { code: 43, desc: "Other commercial crops eg.Teak" },
        { code: 44, desc: "House Sites" },
        { code: 45, desc: "AGRICULTURAL LAND FIT FOR H.S.(A) [నివేశ స్తలములకు తగినటువంటి వ్యవసాయ భూమి(A)]" },
        { code: 46, desc: "LAND ABUTTING NH/SH/ZPP/MPP(A) [NH / SH / ZPP / MPP ని కలిగి ఉన్న భూమి(A)" },
        { code: 47, desc: "Industrial (RURAL)" },
        { code: 48, desc: "Commercial use" },
        { code: 49, desc: "Others eg. Mining, Stones" },
        { code: 50, desc: "Industrial(RURAL-Strucutures)" },
        { code: 98, desc: "Unknown" },
        { code: 99, desc: "Cash (Partition Only)" },
        { code: 99, desc: "MOVABLE" },
        { code: "CC", desc: "Commercial Complex/Banks" },
        { code: "CG", desc: "Central Government Office" },
        { code: "CS", desc: "Commercial/Shops" },
        { code: "CT", desc: "Cinema theatre,Auditoriums" },
        { code: "ED", desc: "Schools,Colleges,Universities" },
        { code: "GY", desc: "Grave Yards" },
        { code: "HL", desc: "Hotels,Restaurants,Lodges" },
        { code: "HS", desc: "House in Slum" },
        { code: "HU", desc: "House" },
        { code: "ID", desc: "Industries" },
        { code: "MH", desc: "Marriage & Function Halls" },
        { code: "NH", desc: "Nursing Homes & Hospitals" },
        { code: "PK", desc: "Parks,Play Grounds" },
        { code: "RA", desc: "Residential Apartments" },
        { code: "RP", desc: "Religious Place" },
        { code: "SG", desc: "State Government Office" },
        { code: "VL", desc: "Vacant Land" }
    ],
    localBody: [
        {code:"1",desc:'MUNICIPAL CORPORATION [మున్సిపల్ కార్పొరేషన్]'},
        {code:"2",desc:'SPL./SELECTION GRADE MUNICIPALITY [స్పెషల్ /సెలెక్షన్ గ్రేడ్మున్సిపాలిటీ]'},
        {code:"3",desc:'OTHER MUNICIPALITY/NOTIFIED AREA [ఇతర మునిసిపాలిటీ / నోటిఫైడ్ ఏరియా]'},
        {code:"4",desc:'MINOR GRAM PANCHAYAT [ చిన్న గ్రామ పంచాయతీ]'},
        {code:"5",desc:'MAJOR GRAM PANCHAYAT [మేజర్ గ్రామ పంచాయితీ]'},
        {code:"6",desc:'Cantonment Board [కంటోన్మెంట్ బోర్డు]'},
        {code:"7",desc:'GRADE/OTHER MUNCIPALITY UNDER UA [అర్బన్ అగ్లామరేషన్ లోని గ్రేడ్ 1 మున్సిపాలిటీ మరియు ఇతర మున్సిపాలిటీ]'},
        {code:"8",desc:'MAJOR GRAM PANCHAYATH UNDER UA [అర్బన్ అగ్లామరేషన్ లోని మేజర్ గ్రామ పంచాయతీ]'}
    ]
}
export default MasterData;
